import "./globals.css";
import { Inter } from "next/font/google";
import Tabs from "../../components/Tabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const resAccount = await fetch(
    `https://mt5.mtapi.be/AccountSummary?id=0d564542-08c2-4540-8861-dd0cfaaa40f1`,
    {
      cache: "no-store",
    }
  );

  const account = await resAccount.json();
  let accountBalance = account.balance;
  let accountEquity = account.equity;
  let formattedaccountBalance = "$" + accountBalance.toLocaleString();
  let formattedaccountEquity = "$" + accountEquity.toLocaleString();

  let convertedtotalFloatingProfit = account?.profit;
  convertedtotalFloatingProfit = convertedtotalFloatingProfit.toFixed(2);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: "flex", gap: 30 }}>
          <p>Account Balance: {formattedaccountBalance}</p>
          <p>Equity: {formattedaccountEquity}</p>
          <div style={{ display: "flex" }}>
            <p>Floating:</p>
            <p>
              {convertedtotalFloatingProfit &&
              convertedtotalFloatingProfit < 0 ? (
                <span style={{ color: "red" }}>
                  {convertedtotalFloatingProfit}
                </span>
              ) : (
                <span style={{ color: "green" }}>
                  {convertedtotalFloatingProfit}
                </span>
              )}
            </p>
          </div>
        </div>
        <Tabs />
        {children}
      </body>
    </html>
  );
}
